export class menuModelo{
    constructor(
        public areaPrincipal:boolean,
        public listaMer:boolean,
        public formMerc:boolean,
        public formProm:boolean,
        public listaServicios:boolean,
        public formServicios:boolean,
        public formDesc:boolean,
        public formImpuestos:boolean,
        public formClient:boolean,
        public listaClientes:boolean,
        public listaDevol:boolean,
        public formDevol:boolean,
        public listaPedido:boolean,
        public formPedido:boolean,
        public formAltaVenta:boolean,
        public formDataVentas:boolean,
        public listaSeg:boolean,
        public formSeg:boolean,
        public listaBancos:boolean,
        public formBancos:boolean,
        public listaCaja:boolean,
        public formCaja:boolean,
        public listaDisp:boolean,
        public formDisp:boolean,
        public listaMon:boolean,
        public formMon:boolean,
    ){}
}