export class trabajadoresModelo {
  constructor(
    public apePaterno: string,
    public apeMaterno: string,
    public nombres: string,
    public edad: number,
    public domicilio_CalleNumero: string,
    public domicilio_cod_postal: string,
    public domicilio_colonias_por_cp:string[],
    public domicilio_colonia_vinculada:string,
    public domicilio_municipio:string,
    public domicilio_estado:string,
    public origen_nacimiento_fecha:string,
    public origen_nacimiento_lugar:string,
    public origen_nacionalidad:string,
    public sexo: 'M' | 'F' | 'Otro' | '',
    public estado_civil: 'Soltero' | 'Casado' | 'Divorciado' | 'Viudo' | 'Unión libre' | '',
    public regimen_trabajador:string,
    public contacto_telefono_tipo:string,
    public contacto_telefono_numero:string,
    public contacto_email:string,
    public documentacion_curp:string,
    public documentacion_afore:string,
    public documentacion_rfc:string,
    
    public documentacion_servicio_militar:string,
    public documentacion_pasaporte_numero:string,
    public documentacion_pasaporte_expide:string,
    public documentacion_pasaporte_vigencia:string,
    public documentacion_pasaporte_list_new:any,
    public documentacion_pasaporte_list_registrados:any,
    public documentacion_visa_numero:string,
    public documentacion_visa_expide:string,
    public documentacion_visa_vigencia:string,
    public documentacion_visa_list_new:any,
    public documentacion_visa_list_registrados:any,
    
    public documentacion_numero_de_seguridad_social:string, 
    public documentacion_licencia_tiene:boolean,
    public documentacion_licencia_nivel:string,
    public documentacion_licencia_clase:string,
    public documentacion_licencia_numero:string,
    public documentacion_licencia_expide:string,
    public documentacion_licencia_fecha_expedicion:string,
    public documentacion_licencia_vigencia:any,
    public documentacion_licencia_permanente:boolean,
    public documentacion_licencia_list_new:any,
    public documentacion_licencia_list_registrados:any,

    public cbancaria_banco_token:string,
    public cbancaria_banco_clave:string,
    public cbancaria_banco_nombre_comercial:string,
    public cbancaria_cuenta:string,
    public cbancaria_clabe_inter:string,
    public cbancaria_sucursal:string,

    public centro_de_trabajo:string,
    public departamento:string,
    public puesto:string,
    public salario_tipo:string,
    public contratacion_tipo:string,
    public contratacion_fecha:string,
    public fecha_alta_en_empresa:string,
    public nomina_periodicidad: string,
    public nomina_moneda: string,
    public nomina_moneda_decimales: number,
    public nomina_salario_diario:string,
    public nomina_salario_integrado:string,
    public tipo_jornada:string,
    public turno:string,
  ) { }
}