export interface InterfProductos {
    c_token: string,
    fechaAlta: number,
    producto: string,
    clasificacion: string,
    proceso: number,
    fecha_delete: number,
    status: boolean,
    administrador: number,
    catalogoSAT: number,
    medida_sat: number,
    imagen: string,
    empresa: number,
    concepto: string,
    codigo: number,
    clave: number,
    descripcion: string,
    unidad_medida: string,
    representa: string,
}
