export interface IntefPromociones {
    token_promocion: string,	
    folio: number,	
    alias: string,	
    concepto: string,	
    cou_porc: boolean,	
    cantidad_base: string,	
    aplicacion: string,	
    fecha_inicio: string,	
    fecha_fin: string,	
    fecha_activacion: string,	
    status_activacion: boolean,	
    fecha_delete: string,	
    status: boolean,	
    empresa: number,
    vinculacion: boolean,
}
