export interface InterfProveedores {
    c_token: string,
    const_sit_fiscal: string,
    forma_pago: string,
    clabe_interbancaria: string,
    estado_cuenta: string,
    apePaterno: string,
    apeMaterno: string,
    nombre: string,
    denominacion_rs: string,
    nombre_com: string,
    sitio_web: string,
    redes_soc: string,
    fecha_nac_const: number,
    zona_horaria: string,
    rfc: string,
    curp: string,
    logotipo: string,
    id_pais: number,
    pais: string,
}
