export class nominaTotalesModelo {
  constructor(
    public salario_diario:string,
    public salario_integrado:string,
    public dias_trabajados:string,
    public faltas:string,
    public sueldo:string,
    public horas_extras_dobles:string,
    public aguinaldo:string,
    public horas_extras_triples:string,
    public vacaciones:string,
    public prima_vacacional:string,
    public reparto_de_utilidades:string,
    public despensa:string,
    public premios_de_asistencia:string,
    public premios_de_puntualidad:string,
    public prima_dominical:string,
    public bno_extra_x_comision_otro_edo:string,
    public indemnizacion:string,
    public prima_de_antiguedad:string,
    public isr_ajustado_por_subsidio:string,
    public total_isr:string,
    public total_imss:string,
    public credito_fonacot:string,
    public credito_infonavit:string,
    public subsidio_empleo:string,
    //public subsidio_empleo_aplicado:string,
    public otras_percepciones:string,
    public otros_pagos:string,
    public total_percepciones:string,
    public otras_deducciones:string,
    public total_deducciones:string,
    public total_efectivo:string,
    public total_en_especie:string,
    public neto_pagado:string,
    public salario_por_hora:string,
    public horas_por_dia:string,
    public u_t_laboradas:string,
  ) { }
}