export class nominaImpuestoModelo {
  constructor(
    public fecha_contabilizacion: string,
    public fecha_vencimiento: string,
    public fecha_presentacion: string,
    public estado: string,
    public estado_entidad: string,
    public ejercicio: string,
    public periodo_inicio: string,
    public periodo_fin: string,
    public fecha_pago: string,
    public tipo_declaracion: string,
    public moneda: string,
    public moneda_decimales: number,
    public total_remuneraciones_erogadas: number,
    public porcent_sobre_total_remuneraciones_erogadas: number,
    public importe_sobre_total_remuneraciones_erogadas: number,
    public complementarias_impuesto_a_cargo: number,
    public complementarias_saldo_a_favor: number,
    public impuesto_actualizado: number,
    public impuesto_descuento: string,
    public impuesto_recargos: number,
    public impuesto_recargos_condonados: number,
    public subsi_n_resolu_impuesto_pagar: number,
    public subsi_n_resolu_recargos: number,
    public compensa_n_resolucion: number,
    public compensa_n_resolu_recargos: number,
    public impuesto_total_a_pagar: number,
    public impuesto_saldo_a_favor: number,
    public observaciones: string,
  ) { }
}